//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.19 at 10:38:22 PM EST 
//


package com.translatable.thebrain.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "attributes",
    "thoughts",
    "links",
    "attributeDatas",
    "entries",
    "attachments"
})
@XmlRootElement(name = "BrainData")
public class BrainData {

    @XmlElement(name = "Source", required = true)
    protected Source source;
    @XmlElement(name = "Attributes")
    protected Attributes attributes;
    @XmlElement(name = "Thoughts")
    protected Thoughts thoughts;
    @XmlElement(name = "Links")
    protected Links links;
    @XmlElement(name = "AttributeDatas")
    protected AttributeDatas attributeDatas;
    @XmlElement(name = "Entries")
    protected Entries entries;
    @XmlElement(name = "Attachments")
    protected Attachments attachments;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link Attributes }
     *     
     */
    public Attributes getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attributes }
     *     
     */
    public void setAttributes(Attributes value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the thoughts property.
     * 
     * @return
     *     possible object is
     *     {@link Thoughts }
     *     
     */
    public Thoughts getThoughts() {
        return thoughts;
    }

    /**
     * Sets the value of the thoughts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Thoughts }
     *     
     */
    public void setThoughts(Thoughts value) {
        this.thoughts = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link Links }
     *     
     */
    public Links getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link Links }
     *     
     */
    public void setLinks(Links value) {
        this.links = value;
    }

    /**
     * Gets the value of the attributeDatas property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeDatas }
     *     
     */
    public AttributeDatas getAttributeDatas() {
        return attributeDatas;
    }

    /**
     * Sets the value of the attributeDatas property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeDatas }
     *     
     */
    public void setAttributeDatas(AttributeDatas value) {
        this.attributeDatas = value;
    }

    /**
     * Gets the value of the entries property.
     * 
     * @return
     *     possible object is
     *     {@link Entries }
     *     
     */
    public Entries getEntries() {
        return entries;
    }

    /**
     * Sets the value of the entries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entries }
     *     
     */
    public void setEntries(Entries value) {
        this.entries = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link Attachments }
     *     
     */
    public Attachments getAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attachments }
     *     
     */
    public void setAttachments(Attachments value) {
        this.attachments = value;
    }

}
