//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.19 at 10:38:22 PM EST 
//


package com.translatable.thebrain.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guid",
    "name",
    "label",
    "creationDateTime",
    "realModificationDateTime",
    "displayModificationDateTime",
    "forgottenDateTime",
    "deletedDateTime",
    "activationDateTime",
    "linksModificationDateTime",
    "isType",
    "color",
    "accessControlType"
})
@XmlRootElement(name = "Thought")
public class Thought {

    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected String name;
    protected String label;
    protected String creationDateTime;
    protected String realModificationDateTime;
    protected String displayModificationDateTime;
    protected String forgottenDateTime;
    protected String deletedDateTime;
    protected String activationDateTime;
    protected String linksModificationDateTime;
    protected String isType;
    protected String color;
    protected String accessControlType;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDateTime(String value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the realModificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealModificationDateTime() {
        return realModificationDateTime;
    }

    /**
     * Sets the value of the realModificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealModificationDateTime(String value) {
        this.realModificationDateTime = value;
    }

    /**
     * Gets the value of the displayModificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayModificationDateTime() {
        return displayModificationDateTime;
    }

    /**
     * Sets the value of the displayModificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayModificationDateTime(String value) {
        this.displayModificationDateTime = value;
    }

    /**
     * Gets the value of the forgottenDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForgottenDateTime() {
        return forgottenDateTime;
    }

    /**
     * Sets the value of the forgottenDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForgottenDateTime(String value) {
        this.forgottenDateTime = value;
    }

    /**
     * Gets the value of the deletedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeletedDateTime() {
        return deletedDateTime;
    }

    /**
     * Sets the value of the deletedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeletedDateTime(String value) {
        this.deletedDateTime = value;
    }

    /**
     * Gets the value of the activationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationDateTime() {
        return activationDateTime;
    }

    /**
     * Sets the value of the activationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationDateTime(String value) {
        this.activationDateTime = value;
    }

    /**
     * Gets the value of the linksModificationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinksModificationDateTime() {
        return linksModificationDateTime;
    }

    /**
     * Sets the value of the linksModificationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinksModificationDateTime(String value) {
        this.linksModificationDateTime = value;
    }

    /**
     * Gets the value of the isType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsType() {
        return isType;
    }

    /**
     * Sets the value of the isType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsType(String value) {
        this.isType = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the accessControlType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessControlType() {
        return accessControlType;
    }

    /**
     * Sets the value of the accessControlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessControlType(String value) {
        this.accessControlType = value;
    }

}
